### ISSUE TITLE
Outdated revision names (DQIII)

### ISSUE THREAD

**Issue by rzumer** [libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System#15]
Source:
https://datomatic.no-intro.org/?page=show_record&s=45&n=0603
https://datomatic.no-intro.org/?page=show_record&s=45&n=0604

The result is that the image is not fetched when using the up-to-date revision label.

Note: Rev 1 was also recently named Rev A.

I will let someone else choose how to fix it, whether it is by renaming, or duplicating the existing entries. It seems to me that there should be parent entries fetched by default if a revision/suffix-specific entry is not present in the list, in order to avoid similar situations.

**Comment by RobLoach** [comment]
We roll with whatever is latest from No-Intro... Latest check was run two weeks ago:
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Nintendo%20-%20Nintendo%20Entertainment%20System.txt#L744-L747

Feel free to rename/fix in a pull request :wink:

**Comment by RobLoach** [comment]
Also depends on when we update the No-Intro db. Last update was Feb 1st:
https://github.com/libretro/libretro-database/pull/795

**Comment by rzumer** [comment]
I prefer waiting for better ways to handle things like alternative images for multi-region titles and the parent/clone scheme as mentioned earlier before contributing to the database, because the current system cannot fulfill my needs. So I will copy the DQIII folders to close this issue, but I do not plan on fixing other mismatched or missing assets for now.

**Comment by RobLoach** [comment]
> I suggest setting up a simple alternative submission system that does not require people to fetch several hundred MB of data to make a change.

Agreed... We'ved considered a few different platforms. One was https://datproject.org . Do you have any suggestions?
