### ISSUE TITLE
Mission Impossible

### ISSUE THREAD

**Issue by 2alek** [libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System#62]
Please check if the game "Mission Impossible (USA).png" has the same names in the Box Arts, Title and Snaps folders.

And congratulations on a great job.

**Comment by masanasake** [comment]
I tried to shove your request in with mine when I made a pull request. If/when it gets approved, let me know if that's what you wanted. Looked like the boxarts had different names than the snaps/titles, so I just added a new entry for the boxarts

**Comment by RobLoach** [comment]
Thanks a lot!
