### ISSUE TITLE
Earth Bound (USA) (Proto)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System#71]
Is it possible to change the metadata for this one? "EarthBound Beginnings (USA, Europe) (Virtual Console)" comes up under it, and given the history, it makes sense, but the name isn't helping anyone. Would be nice to either update it to "EarthBound Beginnings (USA, Europe) (Virtual Console)" or something simplified, or at least make it just "EarthBound (USA) (Proto)". The latter is still confusing because of the SNES game. Just a thought.

**Comment by RobLoach** [comment]
We follow No-Intro Dat-o-matic , so possibly post this question on their forum? https://datomatic.no-intro.org/
